### ISSUE TITLE
Missing release with Swift 4 support

### ISSUE THREAD

**Issue by graphiclife** [rhodgkins/SwiftHTTPStatusCodes#14]
When using carthage (or similar), the 3.2.0 fails to build with Xcode 10.12.

**Comment by wuf810** [comment]
Any chance we could see a version with Swift4 support. Xcode 10.2 now requires it.

**Comment by rhodgkins** [comment]
Release [3.3.0](https://github.com/rhodgkins/SwiftHTTPStatusCodes/releases/tag/3.3.0)

Will release 3.4.0 with Swift 5 / Xcode 10.2 support shortly.

**Comment by rhodgkins** [comment]
Release [3.3.1](https://github.com/rhodgkins/SwiftHTTPStatusCodes/releases/tag/3.3.1) with Swift 5 support.

**Comment by wuf810** [comment]
Thanks @rhodgkins Thats great news and really appreciated that.
