### ISSUE TITLE
Publish SwiftHTTPStatusCodes 3.1.0 for Swift 3 on Cocoapods

### ISSUE THREAD

**Issue by thiagogabriel** [rhodgkins/SwiftHTTPStatusCodes#7]
Hi, apparently https://github.com/rhodgkins/SwiftHTTPStatusCodes/tree/3.1.0 is ready but not yet published on cocoapods. Can you publish it if it is ready?

Thanks.

**Comment by rhodgkins** [comment]
Hello,

 I tried (when I released 3.1.0) there was an error with `pod trunk push`. I'll try again once another RC of CocoaPods 1.1.0 is out.

Cheers,

Rich

**Comment by rhodgkins** [comment]
Oh also for now you should be able to just point your pod file at the 3.1.0 tag

`pod 'HTTPStatusCodes', :git => 'https://github.com/rhodgkins/SwiftHTTPStatusCodes.git', :tag => '3.1.0'`

Cheers,

Rich

**Comment by rhodgkins** [comment]
It looks like CocoaPods 1.1.0 RC 2 has a fix for this (with https://github.com/CocoaPods/CocoaPods/pull/5650) so once that is released I'll push to the trunk!

Cheers,

Rich

**Comment by rhodgkins** [comment]
[Pushed](https://github.com/CocoaPods/Specs/commit/90c40f1bd8fb3738b8e1b725c3ffe9ac284ac9bb)!

Cheers, 

Rich

**Comment by thiagogabriel** [comment]
Thanks @rhodgkins 💯
