### ISSUE TITLE
Please Disable Code Coverage

### ISSUE THREAD

**Issue by ctee-cormant** [rhodgkins/SwiftHTTPStatusCodes#9]
Code coverage has to be disabled for Carthage to work with Xcode 9.

Check Carthage/Carthage#2056 and Carthage/Carthage#2057.

`otool -l -arch all Carthage/Build/iOS/HTTPStatusCodes.framework/HTTPStatusCodes  | grep __llvm_prf`

`
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
  sectname __llvm_prf_cnts
  sectname __llvm_prf_data
  sectname __llvm_prf_names
  sectname __llvm_prf_vnds
`

**Comment by rhodgkins** [comment]
Added in [3.2.0](https://github.com/rhodgkins/SwiftHTTPStatusCodes/releases/tag/3.2.0).
